import './style.css'
import { campaigns } from './game/campaigns'
import { Game, type BattleOptions, type GameSettings } from './game/Game'
import { loadoutsForCampaign } from './game/loadouts'

const savedCampaign = Number(localStorage.getItem('battlefield1937_campaign') ?? 0)
const campaignIndex = Number.isInteger(savedCampaign) && savedCampaign >= 0 && savedCampaign < campaigns.length ? savedCampaign : 0
const campaign = campaigns[campaignIndex]
const battleLoadouts = loadoutsForCampaign(campaign.id)
type CampaignResult = { won: boolean; kills: number; deaths: number; score?: number; completedAt: number }
let campaignResults: Record<string, CampaignResult> = {}
try { campaignResults = JSON.parse(localStorage.getItem('battlefield1937_results') ?? '{}') as Record<string, CampaignResult> } catch { localStorage.removeItem('battlefield1937_results') }
const defaultSettings: GameSettings = { quality: 'high', volume: .8, sensitivity: .0022 }
let settings: GameSettings = { ...defaultSettings }
try { const saved = JSON.parse(localStorage.getItem('battlefield1937_settings') ?? '{}') as Partial<GameSettings>; if (saved.quality === 'low' || saved.quality === 'medium' || saved.quality === 'high') settings.quality = saved.quality; if (typeof saved.volume === 'number') settings.volume = Math.max(0, Math.min(1, saved.volume)); if (typeof saved.sensitivity === 'number') settings.sensitivity = Math.max(.0007, Math.min(.005, saved.sensitivity)) } catch { localStorage.removeItem('battlefield1937_settings') }
let battleOptions: BattleOptions = { difficulty: 'veteran', size: 'standard' }
try { const saved = JSON.parse(localStorage.getItem('battlefield1937_battle') ?? '{}') as Partial<BattleOptions>; if (saved.difficulty === 'recruit' || saved.difficulty === 'veteran' || saved.difficulty === 'elite') battleOptions.difficulty = saved.difficulty; if (saved.size === 'standard' || saved.size === 'reinforced' || saved.size === 'epic') battleOptions.size = saved.size } catch { localStorage.removeItem('battlefield1937_battle') }

document.querySelector<HTMLDivElement>('#app')!.innerHTML = `
<canvas id="game" aria-label="战地1937实时战场"></canvas>
<main id="menu" class="menu">
  <header><p>中国人民抗日战争 1937-1945</p><h1>战地<span>1937</span></h1></header>
  <nav><button id="start" class="primary"><b>进入战场</b><small>${campaign.name} - ${campaign.battlefield}</small></button><div class="battle-options"><span>BOT 难度</span><div><button data-difficulty="recruit">新兵</button><button data-difficulty="veteran">老兵</button><button data-difficulty="elite">精英</button></div><span>兵力规模</span><div><button data-size="standard">标准 11v11</button><button data-size="reinforced">加强 16v16</button><button data-size="epic">史诗 22v22</button></div></div><button id="campaignSelect"><b>选择战役</b><small>${campaign.year} · ${campaign.location}</small></button><button id="warArchive"><b>战争档案</b><small>已完成 ${Object.keys(campaignResults).length} / ${campaigns.length}</small></button><button disabled><b>游戏设置</b><small>开发中</small></button></nav>
  <section class="chronicle" id="chronicle"><div class="chronicle-head"><p>战争全景</p><h2>从淞沪烽火，到湘西反攻</h2></div><div class="campaigns">${campaigns.map((item, index) => { const result = campaignResults[item.id]; return `<button class="campaign-card ${index === campaignIndex ? 'selected' : ''} ${result ? result.won ? 'won' : 'lost' : ''}" data-campaign="${index}" aria-pressed="${index === campaignIndex}"><time>${item.year}</time><h3>${item.name}</h3><p>${item.location} / ${item.battlefield}</p><span>${result ? `${result.won ? '胜利' : '战败'} · ${result.score === undefined ? `击杀 ${result.kills}` : `得分 ${result.score}`}` : item.mode}</span></button>` }).join('')}</div></section>
  <footer>WASD 移动　空格跳跃　鼠标瞄准　左键射击　1/2 切换武器　J 架枪　V 刺刀　Q/E 侧倾　R 装填　Shift 疾跑　Tab 战况</footer>
</main>
<section id="hud" class="hud hidden"><div class="objective"><small>当前任务</small><strong>${campaign.objective}</strong><span>${campaign.name} / ${campaign.location} / ${campaign.date}</span></div><div class="compass"><strong><i id="allyTickets">${campaign.tickets}</i> 中国军队　<span id="flags">${campaign.flags.map(flag => `○${flag.id}`).join('　')}</span>　日军 <b id="enemyTickets">${campaign.tickets}</b></strong><small><span id="matchTime">18:00</span>　·　<span id="heading">北 000°</span></small></div><canvas id="minimap" class="minimap" width="210" height="270"></canvas><div id="capture" class="capture hidden"></div><div id="killfeed" class="killfeed"></div><div class="squad"><small>前线作战小队</small><span id="squadState">小队 3 / 3</span><span id="squadOrder">跟随中</span><span class="squad-help">[T] 标记进攻　[Y] 跟随我　[C] 蹲伏　[Z] 卧倒</span><i id="health"></i><i id="stamina" class="stamina"></i><span id="stance" class="stance">站立</span></div><div class="ammo"><small id="weaponName">中正式步骑枪</small><strong id="ammo">05 / 50</strong><span id="mode">栓动　7.92×57mm</span></div><div id="tankStatus" class="tank-status hidden"><strong id="vehicleIntegrity"></strong><i class="vehicle-health"><b id="vehicleHealthFill"></b></i><small id="vehicleSystems"></small><i class="vehicle-ready"><b id="vehicleReadyFill"></b></i></div><div id="equipment" class="equipment">手雷 [G] ×2</div><div id="grenadeType" class="grenade-type hidden"></div><div id="braceState" class="brace-state hidden"></div><div id="breathState" class="breath-state hidden"></div><div id="actionPrompt" class="action-prompt hidden"></div><div id="grenadeCook" class="grenade-cook hidden"></div><div id="grenadeWarning" class="grenade-warning hidden">⚠ 手雷</div><div class="crosshair" aria-hidden="true"><i></i><i></i><i></i><i></i><b></b></div><div id="tankSight" class="tank-sight hidden"><i></i><b></b><span>37</span></div><div id="tankPip" class="tank-pip hidden"></div><div id="leadPip" class="lead-pip hidden"></div><div id="hit" class="hit">×</div><div id="damage" class="damage"></div><div id="damageDirection" class="damage-direction"></div><div id="feed" class="feed"></div></section>
<section id="scoreboard" class="scoreboard hidden" role="dialog" aria-label="战场记分板" aria-modal="false"><div class="scoreboard-head"><div><small>${campaign.name} · ${campaign.battlefield}</small><h2>战场记分板</h2></div><span>按住 TAB 查看</span></div><div class="score-columns"><article><h3><i></i>中国军队</h3><table><thead><tr><th scope="col">姓名</th><th scope="col">击杀</th><th scope="col">阵亡</th><th scope="col">得分</th><th scope="col">状态</th></tr></thead><tbody id="allyScores"></tbody></table></article><article class="enemy-score"><h3><i></i>日军</h3><table><thead><tr><th scope="col">姓名</th><th scope="col">击杀</th><th scope="col">阵亡</th><th scope="col">得分</th><th scope="col">状态</th></tr></thead><tbody id="enemyScores"></tbody></table></article></div></section>
<section id="death" class="death deploy hidden"><div><p>${campaign.name} · 中国军队</p><h2 id="deployTitle">部署</h2><span id="stats"></span><div class="deploy-layout"><canvas id="deployMap" width="210" height="270"></canvas><div><div id="classGrid" class="class-grid">${battleLoadouts.map((item, index) => `<button class="class-card ${index === 0 ? 'selected' : ''}" data-class="${index}"><b>${item.name}</b><small>${item.weapon}</small><i>${item.role}</i></button>`).join('')}</div><div class="spawn-grid"><button class="spawn selected" data-spawn="base">主基地</button>${campaign.flags.map(flag => `<button class="spawn" data-spawn="${flag.id}" disabled>${flag.id} 点</button>`).join('')}<button class="spawn vehicle-spawn" data-spawn="vehicle-tank" disabled>▣ 维克斯坦克</button><button class="spawn vehicle-spawn" data-spawn="vehicle-transport" disabled>▰ 运兵卡车</button><button class="spawn vehicle-spawn" data-spawn="vehicle-plane" disabled>✈ 霍克战斗机</button></div></div></div><button id="respawn">投入战斗</button></div></section>
<section id="end" class="death hidden"><div><p>${campaign.name} · ${campaign.mode}</p><h2 id="endTitle">胜利</h2><blockquote id="endText"></blockquote><span id="endStats"></span><button id="restart">${campaignIndex < campaigns.length - 1 ? `继续战争 · ${campaigns[campaignIndex + 1].name}` : '查看战争档案'}</button></div></section>`
if (campaign.id === 'baituan') {
  const vehicleButtons = document.querySelectorAll<HTMLButtonElement>('.vehicle-spawn'); vehicleButtons[0].textContent = '▣ 九七式中战车（缴获）'; vehicleButtons[1].textContent = '▰ 改装民用卡车'; vehicleButtons[2].textContent = '✈ 一式战“隼”（缴获）'
  document.querySelector<HTMLElement>('#death p')!.textContent = `${campaign.name} · 八路军`; document.querySelector<HTMLElement>('.score-columns article h3')!.innerHTML = '<i></i>八路军'; document.querySelector<HTMLElement>('.compass strong')!.childNodes[1].textContent = ' 八路军　'
}
document.querySelector<HTMLDivElement>('#app')!.insertAdjacentHTML('beforeend', `<section id="pause" class="pause-menu hidden" role="dialog" aria-modal="true" aria-labelledby="pauseTitle"><div><p>${campaign.name} · ${campaign.battlefield}</p><h2 id="pauseTitle">战斗暂停</h2><span>单机战场模拟已冻结</span><button id="resumeBattle" class="primary">继续战斗</button><button id="restartBattle">重新部署本场会战</button><button id="leaveBattle">撤回主菜单</button></div></section>`)
document.querySelector<HTMLDivElement>('#app')!.insertAdjacentHTML('beforeend', `<section id="downed" class="downed-scene hidden" aria-live="assertive"><div><small>战场仍在继续</small><strong>你已阵亡</strong><span id="downedStats"></span><blockquote id="deathQuote"></blockquote></div></section>`)

document.querySelector<HTMLDivElement>('#app')!.insertAdjacentHTML('beforeend', `<section id="settingsDialog" class="settings-dialog hidden" role="dialog" aria-modal="true" aria-labelledby="settingsTitle"><div class="settings-panel"><header><p>系统配置</p><h2 id="settingsTitle">游戏设置</h2><button id="closeSettings" type="button" aria-label="关闭游戏设置">关闭</button></header><div class="settings-fields"><label><span><b>画面质量</b><small>调整分辨率比例与动态阴影</small></span><select id="quality"><option value="high">高</option><option value="medium">中</option><option value="low">低</option></select></label><label><span><b>主音量</b><small>枪声、爆炸与载具音效</small></span><input id="volume" type="range" min="0" max="100" step="1"><output id="volumeValue" for="volume"></output></label><label><span><b>鼠标灵敏度</b><small>步兵与载具观察速度</small></span><input id="sensitivity" type="range" min="1" max="100" step="1"><output id="sensitivityValue" for="sensitivity"></output></label></div><footer><button id="resetSettings" type="button">恢复默认</button><button id="saveSettings" class="primary" type="button">保存并返回</button></footer></div></section>`)
document.querySelector<HTMLDivElement>('#app')!.insertAdjacentHTML('beforeend', `<section id="touchUI" class="touch-ui" aria-label="触控操作界面"><div id="touchStickZone" class="touch-stick-zone"><div id="touchStick" class="touch-stick"><i></i></div></div><div id="touchLook" class="touch-look" aria-hidden="true"></div><button class="touch-btn touch-fire" data-touch="fire">开火</button><button class="touch-btn touch-aim" data-touch="aim">瞄准</button><button class="touch-btn touch-reload" data-touch="reload">装填</button><button class="touch-btn touch-switch" data-touch="switch">武器</button><button class="touch-btn touch-jump" data-touch="jump">跳跃</button><button class="touch-btn touch-brace" data-touch="brace">架枪</button><button class="touch-btn touch-crouch" data-touch="crouch">蹲 / 趴</button><button class="touch-btn touch-grenade" data-touch="grenade">手雷</button><button class="touch-btn touch-grenade-type" data-touch="grenade-type">雷种</button><button class="touch-btn touch-smoke" data-touch="smoke">烟雾</button><button class="touch-btn touch-heal" data-touch="heal">包扎</button><button class="touch-btn touch-melee" data-touch="melee">刺刀</button><button class="touch-btn touch-interact" data-touch="interact">交互</button></section>`)

const settingsButton = document.querySelectorAll<HTMLButtonElement>('#menu nav > button')[3]; settingsButton.disabled = false; settingsButton.id = 'openSettings'; settingsButton.querySelector('small')!.textContent = '画质 · 音量 · 操控'

const $ = <T extends Element>(selector: string) => document.querySelector<T>(selector)!
document.querySelector<HTMLElement>('.objective span')!.textContent += ` / ${campaign.weather}`
const hud = $('#hud'), menu = $('#menu'), pause = $('#pause'), downed = $('#downed'), downedStats = $('#downedStats'), deathQuote = $('#deathQuote'), ammo = $('#ammo'), mode = $('#mode'), heading = $('#heading'), matchTime = $('#matchTime'), weaponName = $('#weaponName'), tankStatus = $('#tankStatus'), vehicleIntegrity = $('#vehicleIntegrity'), vehicleSystems = $('#vehicleSystems'), vehicleHealthFill = $<HTMLElement>('#vehicleHealthFill'), vehicleReadyFill = $<HTMLElement>('#vehicleReadyFill'), equipment = $('#equipment'), grenadeType = $('#grenadeType'), grenadeCook = $('#grenadeCook'), braceState = $('#braceState'), breathState = $('#breathState'), actionPrompt = $('#actionPrompt'), grenadeWarning = $('#grenadeWarning'), squadState = $('#squadState'), squadOrder = $('#squadOrder'), hit = $('#hit'), damage = $('#damage'), damageDirection = $<HTMLElement>('#damageDirection'), feed = $('#feed'), killfeed = $('#killfeed'), tankSight = $('#tankSight'), tankPip = $<HTMLElement>('#tankPip'), leadPip = $<HTMLElement>('#leadPip'), health = $<HTMLElement>('#health'), stamina = $<HTMLElement>('#stamina'), stance = $('#stance'), scoreboard = $('#scoreboard'), allyScores = $('#allyScores'), enemyScores = $('#enemyScores'), death = $('#death'), deployTitle = $('#deployTitle'), stats = $('#stats'), respawn = $<HTMLButtonElement>('#respawn'), end = $('#end'), endTitle = $('#endTitle'), endText = $('#endText'), endStats = $('#endStats'), allyTickets = $('#allyTickets'), enemyTickets = $('#enemyTickets'), flags = $('#flags'), capture = $('#capture'), minimap = $<HTMLCanvasElement>('#minimap'), deployMap = $<HTMLCanvasElement>('#deployMap')
const deathQuotes = ['一寸山河一寸血，战场不会因一个人的倒下而停下。', '阵地仍在争夺，下一批增援已经在路上。', '活着的人继续前进，倒下的人留在这片土地上。', '这不是任务失败，只是这名士兵的战斗结束了。']
let deployTimer = 0
let selectedClass = 0, selectedSpawn = 'base'
let shownLoadout = battleLoadouts[0]
const showDeployment = (wasKilled: boolean) => { document.body.classList.remove('touch-game'); deployTitle.textContent = wasKilled ? '阵亡' : '部署'; if (!wasKilled) { stats.textContent = '选择兵种与投入位置'; respawn.disabled = false; respawn.textContent = '投入战斗' } death.classList.remove('hidden') }
const drawMap = (canvas: HTMLCanvasElement, value: Parameters<NonNullable<ConstructorParameters<typeof Game>[1]['tactical']>>[0]) => { const context = canvas.getContext('2d')!, width = canvas.width, height = canvas.height, point = (x: number, z: number): [number, number] => [width / 2 + x / 14 * width * .42, (z + 60) / 120 * height]; context.fillStyle = '#111711'; context.fillRect(0, 0, width, height); context.fillStyle = '#303531'; context.fillRect(width * .31, 0, width * .38, height); context.strokeStyle = 'rgba(190,174,130,.2)'; context.lineWidth = 1; for (let z = -40; z <= 40; z += 20) { const [, y] = point(0, z); context.beginPath(); context.moveTo(0, y); context.lineTo(width, y); context.stroke() } for (const [id, x, z, owner, active] of value.flags) { const [px, py] = point(x, z); context.globalAlpha = active ? 1 : .35; context.fillStyle = owner === 'ally' ? '#79a9d5' : owner === 'enemy' ? '#d06b5a' : '#b9b5a5'; context.beginPath(); context.arc(px, py, 9, 0, Math.PI * 2); context.fill(); if (active) { context.strokeStyle = '#ffe09a'; context.lineWidth = 2; context.stroke() } context.fillStyle = '#111'; context.font = 'bold 10px sans-serif'; context.textAlign = 'center'; context.fillText(id, px, py + 3.5); context.globalAlpha = 1 } for (const [id, x, z, destroyed] of value.depots) { const [px, py] = point(x, z); context.fillStyle = destroyed ? '#55564f' : '#d39b52'; context.fillRect(px - 6, py - 6, 12, 12); context.fillStyle = '#161713'; context.font = 'bold 8px sans-serif'; context.textAlign = 'center'; context.fillText(id, px, py + 3) } const [playerX, playerZ, yaw] = value.player; for (const [x, z, team] of value.infantry) { if (team === 'enemy' && Math.hypot(x - playerX, z - playerZ) > 28) continue; const [px, py] = point(x, z); context.fillStyle = team === 'ally' ? '#8cc0e9' : '#e47a67'; context.fillRect(px - 2, py - 2, 4, 4) } for (const [x, z, team] of value.tanks) { if (team === 'enemy' && Math.hypot(x - playerX, z - playerZ) > 45) continue; const [px, py] = point(x, z); context.strokeStyle = team === 'ally' ? '#8cc0e9' : '#e47a67'; context.lineWidth = 2; context.strokeRect(px - 4, py - 6, 8, 12) } const [px, py] = point(playerX, playerZ); context.save(); context.translate(px, py); context.rotate(-yaw); context.fillStyle = '#fff4b5'; context.beginPath(); context.moveTo(0, -8); context.lineTo(-5, 6); context.lineTo(5, 6); context.closePath(); context.fill(); context.restore() }
const game = new Game($<HTMLCanvasElement>('#game'), {
  ammo(m, r, loading) { ammo.textContent = `${String(m).padStart(2, '0')} / ${String(r).padStart(2, '0')}`; mode.textContent = loading ? '装填中' : shownLoadout.mode },
  equipment(grenades, aid, medkit, builds, buildName, mortarAmmo, mortarPlaced, prompt) { const id = battleLoadouts[selectedClass].id; equipment.textContent = `手雷 [G] ×${grenades}　烟雾 [X]　绷带 [H] ×${aid}${id === 'medic' ? `　医疗箱 [B] ${medkit ? '可用' : '已部署'}` : id === 'engineer' ? `　${buildName} [B] ×${builds}　[5] 切换　维修 [F]` : id === 'mortar' ? `　迫击炮 [B] ${mortarPlaced ? '已架设' : '背负'}　炮弹 ×${mortarAmmo}` : ''}`; actionPrompt.textContent = prompt; actionPrompt.classList.toggle('hidden', !prompt) },
  grenadeMode(value, count) { grenadeType.textContent = value === 'anti-tank' ? `反坦克手雷 ×${count} · [4] 切换` : `破片手雷 · [4] 切换`; grenadeType.classList.toggle('hidden', battleLoadouts[selectedClass].id !== 'anti-tank'); grenadeType.classList.toggle('anti-tank', value === 'anti-tank') },
  grenadeCook(remaining) { grenadeCook.textContent = remaining === undefined ? '' : `引信 ${remaining.toFixed(1)} 秒 · 松开 G 投掷`; grenadeCook.classList.toggle('hidden', remaining === undefined); grenadeCook.classList.toggle('danger', remaining !== undefined && remaining < 1.2) },
  brace(canBrace, braced) { braceState.textContent = braced ? '▙ 已架枪' : '[J] 架枪'; braceState.classList.toggle('hidden', !canBrace && !braced); braceState.classList.toggle('active', braced) },
  breath(scoped, holding, exhausted) { breathState.textContent = exhausted ? '呼吸紊乱' : holding ? '屏息中' : '[Shift] 屏息'; breathState.classList.toggle('hidden', !scoped); breathState.classList.toggle('holding', holding); breathState.classList.toggle('exhausted', exhausted) },
  grenadeWarning(show) { grenadeWarning.classList.toggle('hidden', !show) },
  suppression(value) { (hud as HTMLElement).style.setProperty('--suppression', String(value)); hud.classList.toggle('suppressed', value > .04) },
  damageDirection(angle, strength) { damageDirection.style.setProperty('--damage-angle', `${angle}rad`); damageDirection.style.setProperty('--damage-strength', String(strength)); damageDirection.classList.remove('show'); void damageDirection.offsetWidth; damageDirection.classList.add('show') },
  downed(kills, deaths) { document.body.classList.remove('touch-game'); scoreboard.classList.add('hidden'); hud.classList.add('hidden'); downedStats.textContent = `击杀 ${kills}　阵亡 ${deaths}`; deathQuote.textContent = deathQuotes[Math.floor(Math.random() * deathQuotes.length)]; downed.classList.remove('hidden') },
  vehicle(active, hp, ready, name = '维克斯 6 吨轻型坦克', vehicleMode = '37mm 主炮', maxHp = 100, readiness = ready ? 1 : 0) { hud.classList.toggle('in-vehicle', active); tankStatus.classList.toggle('hidden', !active); if (active) { braceState.classList.add('hidden'); breathState.classList.add('hidden'); const transport = name.includes('卡车'), aircraft = name.includes('战斗机') || name.includes('隼') || name.includes('伊-16') || name.includes('轻爆机'); weaponName.textContent = name; ammo.textContent = transport ? 'WASD' : ready ? 'READY' : '装填中'; mode.textContent = vehicleMode; vehicleIntegrity.textContent = `${aircraft ? '机体' : name.includes('炮') ? '炮位' : '车体'} ${Math.max(0, Math.ceil(hp))} / ${maxHp}`; vehicleSystems.textContent = vehicleMode; vehicleHealthFill.style.width = `${Math.max(0, Math.min(100, hp / maxHp * 100))}%`; vehicleReadyFill.style.width = `${Math.max(0, Math.min(100, readiness * 100))}%`; tankStatus.classList.toggle('critical', hp / maxHp < .3); tankStatus.classList.toggle('loading', !ready) } },
  tankSight(active, gunnerView, ready, pipX, pipY) { hud.classList.toggle('tank-gunner', active && gunnerView); tankSight.classList.toggle('hidden', !active); tankSight.classList.toggle('loading', !ready); tankPip.classList.toggle('hidden', !active || pipX === undefined || pipY === undefined); if (pipX !== undefined && pipY !== undefined) { tankPip.style.left = `${pipX}px`; tankPip.style.top = `${pipY}px` } },
  emplacementLead(x, y) { leadPip.classList.toggle('hidden', x === undefined || y === undefined); if (x !== undefined && y !== undefined) { leadPip.style.left = `${x}px`; leadPip.style.top = `${y}px` } },
  movement(value, valueStance) { stamina.style.setProperty('--stamina', `${value * 100}%`); stance.textContent = valueStance === 'stand' ? '站立' : valueStance === 'crouch' ? '蹲伏' : '卧倒' },
  tactical(value) { drawMap(minimap, value); drawMap(deployMap, value); const degrees = (value.player[2] * 180 / Math.PI % 360 + 360) % 360, cardinals = ['北', '东北', '东', '东南', '南', '西南', '西', '西北']; heading.textContent = `${cardinals[Math.round(degrees / 45) % 8]} ${String(Math.round(degrees)).padStart(3, '0')}°` },
  scoreboard(allies, enemies) { const render = (rows: typeof allies) => rows.map(row => `<tr class="${row.player ? 'player-row' : ''} ${row.alive ? '' : 'dead-row'}"><th scope="row">${row.name}<small>${row.player ? '你 · ' : ''}${row.role ?? ''}</small></th><td>${row.kills}</td><td>${row.deaths}</td><td>${row.score}</td><td><span>${row.alive ? '作战中' : '等待增援'}</span></td></tr>`).join(''); allyScores.innerHTML = render(allies); enemyScores.innerHTML = render(enemies) },
  loadout(value) { shownLoadout = value; weaponName.textContent = value.weapon; mode.textContent = value.mode },
  aim(value) { hud.classList.toggle('aiming', value) },
  squad(alive, total, order) { squadState.textContent = `小队 ${alive} / ${total}`; squadOrder.textContent = order },
  hit(kill, headshot = false) { hit.textContent = headshot ? '◆' : kill ? '✕' : '×'; hit.className = `hit show ${kill ? 'kill' : ''} ${headshot ? 'headshot' : ''}`; setTimeout(() => hit.className = 'hit', 220) },
  health(value, damaged = true) { health.style.setProperty('--hp', `${value}%`); if (damaged) { damage.classList.remove('flash'); requestAnimationFrame(() => damage.classList.add('flash')) } },
  kill(value, target = '日军步兵', headshot = false) { feed.textContent = `${headshot ? '爆头　' : '击杀　'}${target}　+${target.includes('战车') ? 300 : headshot ? 125 : 100}\n本次作战 ${value} 人` },
  objectiveScore(points, label, total) { feed.textContent = `${label}　+${points}\n当前得分 ${total}`; feed.classList.remove('objective-score'); void (feed as HTMLElement).offsetWidth; feed.classList.add('objective-score') },
  combatKill(attacker, attackerTeam, victim, victimTeam, headshot = false) { const row = document.createElement('div'); row.innerHTML = `<b class="${attackerTeam}">${attacker}</b><i>${headshot ? '☠' : '✕'}</i><b class="${victimTeam}">${victim}</b>`; killfeed.prepend(row); while (killfeed.children.length > 6) killfeed.lastElementChild?.remove(); window.setTimeout(() => row.classList.add('fade'), 5200); window.setTimeout(() => row.remove(), 6200) },
  death(kills, deaths) { document.body.classList.remove('touch-game'); downed.classList.add('hidden'); scoreboard.classList.add('hidden'); hud.classList.add('hidden'); deployTitle.textContent = '阵亡'; stats.textContent = `击杀 ${kills}　阵亡 ${deaths}`; death.classList.remove('hidden'); respawn.disabled = true; let left = 5; respawn.textContent = `增援抵达 ${left}`; clearInterval(deployTimer); deployTimer = window.setInterval(() => { left--; respawn.textContent = left > 0 ? `增援抵达 ${left}` : '重新部署'; if (left <= 0) { clearInterval(deployTimer); respawn.disabled = false } }, 1000) },
  battle(tickets, state, progress, spawns, seconds) { const ticketLabel = (value: number) => Number.isFinite(value) ? String(value) : '∞'; allyTickets.textContent = ticketLabel(tickets[0]); enemyTickets.textContent = ticketLabel(tickets[1]); flags.textContent = state; matchTime.textContent = `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; matchTime.classList.toggle('urgent', seconds <= 60); capture.textContent = progress ? `正在争夺 ${progress}` : ''; capture.classList.toggle('hidden', !progress); document.querySelectorAll<HTMLButtonElement>('.spawn').forEach(button => { if (button.dataset.spawn === 'base') return; button.disabled = !spawns.includes(button.dataset.spawn!); if (button.disabled && button.dataset.spawn === selectedSpawn) { selectedSpawn = 'base'; document.querySelectorAll('.spawn').forEach(x => x.classList.toggle('selected', x.getAttribute('data-spawn') === 'base')) } }) },
  end(won, kills, deaths, score) { document.body.classList.remove('touch-game'); clearInterval(deployTimer); campaignResults[campaign.id] = { won, kills, deaths, score, completedAt: Date.now() }; localStorage.setItem('battlefield1937_results', JSON.stringify(campaignResults)); const card = document.querySelector<HTMLElement>(`.campaign-card[data-campaign="${campaignIndex}"]`); card?.classList.remove('won', 'lost'); card?.classList.add(won ? 'won' : 'lost'); const result = card?.querySelector('span'); if (result) result.textContent = `${won ? '胜利' : '战败'} · 得分 ${score}`; const archiveCount = document.querySelector<HTMLElement>('#warArchive small'); if (archiveCount) archiveCount.textContent = `已完成 ${Object.keys(campaignResults).length} / ${campaigns.length}`; downed.classList.add('hidden'); scoreboard.classList.add('hidden'); death.classList.add('hidden'); hud.classList.add('hidden'); endTitle.textContent = won ? '胜利' : '战败'; endTitle.className = won ? 'win' : 'lose'; endText.textContent = won ? `${campaign.battlefield}仍在我军控制之下。部队将转赴下一处战场。` : `${campaign.battlefield}失守，但战争尚未结束，部队转入下一道防线。`; endStats.textContent = `得分 ${score}　击杀 ${kills}　阵亡 ${deaths}　战争进度 ${campaignIndex + 1} / ${campaigns.length}`; end.classList.remove('hidden') },
}, campaign)
game.configureBattle(battleOptions)
game.configure(settings)
void game
const battleTicketCount = () => ({ standard: 330, reinforced: 430, epic: 540 })[battleOptions.size]
const syncBattleOptions = () => { document.querySelectorAll<HTMLButtonElement>('[data-difficulty]').forEach(button => button.classList.toggle('selected', button.dataset.difficulty === battleOptions.difficulty)); document.querySelectorAll<HTMLButtonElement>('[data-size]').forEach(button => button.classList.toggle('selected', button.dataset.size === battleOptions.size)); allyTickets.textContent = String(battleTicketCount()); enemyTickets.textContent = String(battleTicketCount()) }
document.querySelectorAll<HTMLButtonElement>('[data-difficulty]').forEach(button => button.addEventListener('click', () => { battleOptions = { ...battleOptions, difficulty: button.dataset.difficulty as BattleOptions['difficulty'] }; localStorage.setItem('battlefield1937_battle', JSON.stringify(battleOptions)); game.configureBattle(battleOptions); syncBattleOptions() }))
document.querySelectorAll<HTMLButtonElement>('[data-size]').forEach(button => button.addEventListener('click', () => { battleOptions = { ...battleOptions, size: button.dataset.size as BattleOptions['size'] }; localStorage.setItem('battlefield1937_battle', JSON.stringify(battleOptions)); game.configureBattle(battleOptions); syncBattleOptions() }))
syncBattleOptions()
const settingsDialog = $<HTMLElement>('#settingsDialog'), qualityInput = $<HTMLSelectElement>('#quality'), volumeInput = $<HTMLInputElement>('#volume'), sensitivityInput = $<HTMLInputElement>('#sensitivity'), volumeValue = $<HTMLOutputElement>('#volumeValue'), sensitivityValue = $<HTMLOutputElement>('#sensitivityValue')
const sensitivityPercent = () => Math.round(1 + (settings.sensitivity - .0007) / .0043 * 99)
const syncSettings = () => { qualityInput.value = settings.quality; volumeInput.value = String(Math.round(settings.volume * 100)); sensitivityInput.value = String(sensitivityPercent()); volumeValue.value = `${volumeInput.value}%`; sensitivityValue.value = sensitivityInput.value }
const applySettings = (persist = false) => { settings = { quality: qualityInput.value as GameSettings['quality'], volume: Number(volumeInput.value) / 100, sensitivity: .0007 + (Number(sensitivityInput.value) - 1) / 99 * .0043 }; volumeValue.value = `${volumeInput.value}%`; sensitivityValue.value = sensitivityInput.value; game.configure(settings); if (persist) localStorage.setItem('battlefield1937_settings', JSON.stringify(settings)) }
const openSettings = () => { syncSettings(); settingsDialog.classList.remove('hidden'); menu.setAttribute('inert', ''); $<HTMLButtonElement>('#closeSettings').focus() }
const closeSettings = (persist = true) => { if (persist) applySettings(true); settingsDialog.classList.add('hidden'); menu.removeAttribute('inert'); settingsButton.focus() }
settingsButton.addEventListener('click', openSettings)
qualityInput.addEventListener('change', () => applySettings())
volumeInput.addEventListener('input', () => applySettings())
sensitivityInput.addEventListener('input', () => applySettings())
$<HTMLButtonElement>('#closeSettings').addEventListener('click', () => closeSettings())
$<HTMLButtonElement>('#saveSettings').addEventListener('click', () => closeSettings())
$<HTMLButtonElement>('#resetSettings').addEventListener('click', () => { settings = { ...defaultSettings }; syncSettings(); applySettings() })
settingsDialog.addEventListener('click', event => { if (event.target === settingsDialog) closeSettings() })
addEventListener('keydown', event => { if (event.code === 'Escape' && !settingsDialog.classList.contains('hidden')) { event.preventDefault(); closeSettings() } })
const touchCapable = matchMedia('(pointer: coarse)').matches || navigator.maxTouchPoints > 0
if (touchCapable) document.body.classList.add('touch-capable')
if (touchCapable) {
  const stickZone = $<HTMLElement>('#touchStickZone'), stick = $<HTMLElement>('#touchStick'), look = $<HTMLElement>('#touchLook'); let stickId = -1, stickX = 0, stickY = 0; const lookTouches = new Map<number, [number, number]>()
  const moveStick = (x: number, y: number) => { const dx = x - stickX, dy = y - stickY, distance = Math.hypot(dx, dy), radius = 58, scale = distance > radius ? radius / distance : 1; stick.style.setProperty('--knob-x', `${dx * scale}px`); stick.style.setProperty('--knob-y', `${dy * scale}px`); game.touchMove(Math.max(-1, Math.min(1, dx / radius)), Math.max(-1, Math.min(1, dy / radius))) }
  stickZone.addEventListener('touchstart', event => { if (stickId >= 0) return; const touch = event.changedTouches[0], bounds = stickZone.getBoundingClientRect(); stickId = touch.identifier; stickX = touch.clientX; stickY = touch.clientY; stick.style.left = `${touch.clientX - bounds.left - 64}px`; stick.style.top = `${touch.clientY - bounds.top - 64}px`; stick.classList.add('active'); moveStick(touch.clientX, touch.clientY); event.preventDefault() }, { passive: false })
  stickZone.addEventListener('touchmove', event => { const touch = [...event.changedTouches].find(item => item.identifier === stickId); if (touch) { moveStick(touch.clientX, touch.clientY); event.preventDefault() } }, { passive: false })
  const endStick = (event: TouchEvent) => { if (![...event.changedTouches].some(item => item.identifier === stickId)) return; stickId = -1; game.touchMove(0, 0); stick.classList.remove('active'); stick.removeAttribute('style'); event.preventDefault() }; stickZone.addEventListener('touchend', endStick, { passive: false }); stickZone.addEventListener('touchcancel', endStick, { passive: false })
  look.addEventListener('touchstart', event => { for (const touch of event.changedTouches) lookTouches.set(touch.identifier, [touch.clientX, touch.clientY]); event.preventDefault() }, { passive: false })
  look.addEventListener('touchmove', event => { for (const touch of event.changedTouches) { const previous = lookTouches.get(touch.identifier); if (!previous) continue; game.touchLook(touch.clientX - previous[0], touch.clientY - previous[1]); lookTouches.set(touch.identifier, [touch.clientX, touch.clientY]) } event.preventDefault() }, { passive: false })
  const endLook = (event: TouchEvent) => { for (const touch of event.changedTouches) lookTouches.delete(touch.identifier); event.preventDefault() }; look.addEventListener('touchend', endLook, { passive: false }); look.addEventListener('touchcancel', endLook, { passive: false })
  document.querySelectorAll<HTMLButtonElement>('[data-touch]').forEach(button => { const action = button.dataset.touch as Parameters<Game['touchAction']>[0]; let longPress = 0, lastX = 0, lastY = 0; button.addEventListener('touchstart', event => { event.preventDefault(); const touch = event.changedTouches[0]; lastX = touch.clientX; lastY = touch.clientY; button.classList.add('pressed'); if (action === 'crouch') longPress = window.setTimeout(() => { longPress = 0; game.touchAction('prone') }, 430); else game.touchAction(action, true) }, { passive: false }); button.addEventListener('touchmove', event => { const touch = event.changedTouches[0]; if (action === 'fire') game.touchLook(touch.clientX - lastX, touch.clientY - lastY); if (longPress && Math.hypot(touch.clientX - lastX, touch.clientY - lastY) > 18) { clearTimeout(longPress); longPress = 0 } lastX = touch.clientX; lastY = touch.clientY; event.preventDefault() }, { passive: false }); const release = (event: TouchEvent) => { event.preventDefault(); button.classList.remove('pressed'); if (action === 'fire' || action === 'grenade') game.touchAction(action, false); if (action === 'crouch' && longPress) { clearTimeout(longPress); longPress = 0; game.touchAction('crouch') } }; button.addEventListener('touchend', release, { passive: false }); button.addEventListener('touchcancel', release, { passive: false }) })
  document.querySelectorAll<HTMLButtonElement>('[data-touch]').forEach(button => button.addEventListener('click', () => { const action = button.dataset.touch as Parameters<Game['touchAction']>[0]; if (action === 'fire' || action === 'grenade') { game.touchAction(action, true); setTimeout(() => game.touchAction(action, false), 90) } else game.touchAction(action) }))
}
$('#start').addEventListener('click', () => {
  game.unlockAudio()
  menu.classList.add('leaving')
  setTimeout(() => {
    menu.classList.add('hidden')
    game.start()
    showDeployment(false)
  }, 260)
})
respawn.addEventListener('click', () => {
  death.classList.add('hidden')
  hud.classList.remove('hidden')
  if (touchCapable) document.body.classList.add('touch-game')
  game.respawn(selectedClass, selectedSpawn)
})
document.querySelectorAll<HTMLButtonElement>('.class-card').forEach(button => button.addEventListener('click', () => { selectedClass = Number(button.dataset.class); document.querySelectorAll('.class-card').forEach(x => x.classList.toggle('selected', x === button)) }))
document.querySelectorAll<HTMLButtonElement>('.spawn').forEach(button => button.addEventListener('click', () => { selectedSpawn = button.dataset.spawn!; document.querySelectorAll('.spawn').forEach(x => x.classList.toggle('selected', x === button)) }))
document.querySelectorAll<HTMLButtonElement>('.campaign-card').forEach(button => button.addEventListener('click', () => { const index = Number(button.dataset.campaign); if (index === campaignIndex) { $<HTMLButtonElement>('#start').focus(); return } localStorage.setItem('battlefield1937_campaign', String(index)); location.reload() }))
$('#campaignSelect').addEventListener('click', () => { document.querySelector<HTMLButtonElement>('.campaign-card.selected')?.focus(); $('#chronicle').scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth', block: 'center' }) })
$('#warArchive').addEventListener('click', () => { $('#chronicle').scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth', block: 'center' }); document.querySelector<HTMLButtonElement>('.campaign-card.won, .campaign-card.lost, .campaign-card.selected')?.focus() })
$('#restart').addEventListener('click', () => { if (campaignIndex < campaigns.length - 1) { localStorage.setItem('battlefield1937_campaign', String(campaignIndex + 1)); location.reload(); return } end.classList.add('hidden'); menu.classList.remove('hidden'); document.body.classList.remove('playing'); $('#chronicle').scrollIntoView({ block: 'center' }) })
$<HTMLButtonElement>('#resumeBattle').addEventListener('click', () => { pause.classList.add('hidden'); game.setPaused(false); $<HTMLCanvasElement>('#game').requestPointerLock() })
$<HTMLButtonElement>('#restartBattle').addEventListener('click', () => { pause.classList.add('hidden'); hud.classList.add('hidden'); game.restart(); showDeployment(false) })
$<HTMLButtonElement>('#leaveBattle').addEventListener('click', () => location.reload())
addEventListener('pointerlockchange', () => { if (document.pointerLockElement || hud.classList.contains('hidden') || !death.classList.contains('hidden') || !end.classList.contains('hidden') || !pause.classList.contains('hidden')) return; document.body.classList.remove('touch-game'); scoreboard.classList.add('hidden'); game.setPaused(true); pause.classList.remove('hidden'); $<HTMLButtonElement>('#resumeBattle').focus() })
addEventListener('keydown', event => { if (event.code !== 'Tab' || hud.classList.contains('hidden')) return; event.preventDefault(); scoreboard.classList.remove('hidden') })
addEventListener('keyup', event => { if (event.code !== 'Tab') return; event.preventDefault(); scoreboard.classList.add('hidden') })
